config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/search', to: 'search#index'

  resources :apps, only: :show
end

app/models/app.rb
class App < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_action :set_app, only: [:show]

  # GET /apps
  # GET /apps.json
  def index
    @apps = App.all
  end

  # GET /apps/1
  # GET /apps/1.json
  def show
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app
      @app = App.find(params[:id])
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # GET /
  def index
    @most_downloaded = App.order(downloads: :desc).limit(5)
    @highest_rated = App.order(rating: :desc).limit(5)
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    @apps = App.where("name LIKE ?", "%#{params[:query]}%")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
  require 'digest/md5'

  def app_image(app)
    color = Digest::MD5.hexdigest(app.name)[0..5]
    "https://dummyimage.com/300x300/#{color}/ffffff.png&text=#{app.name}"
  end
end

app/views/apps/_app_cards.html.erb
<h1 class="header"><%= name %></h1>
<div class="ui divider"></div>
<div class="ui link cards app-cards">
  <% app_list.each do |app| %>
    <a class="card" href="<%= app_path(app) %>">
      <div class="image">
        <img src="<%= app_image(app) %>">
      </div>
      <div class="content">
        <div class="header"><%= app.name %></div>
        <div class="meta"><%= app.author %></div>
        <div class="description"><%= truncate app.description, length: 100, seperator: /\w+/ %></div>
      </div>
      <div class="extra content">
        <span class="right floated">
          <i class="star icon"></i> <%= app.rating %>
        </span>
        <span>
          <i class="arrow alternate circle down outline icon"></i> <%= number_to_human app.downloads %>
        </span>
      </div>
    </a>
  <% end %>
</div>

app/views/apps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Apps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rating</th>
      <th>Release date</th>
      <th>Description</th>
      <th>Downloads</th>
      <th>Rated times</th>
      <th>Author</th>
      <th>Version</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apps.each do |app| %>
      <tr>
        <td><%= app.name %></td>
        <td><%= app.rating %></td>
        <td><%= app.release_date %></td>
        <td><%= app.description %></td>
        <td><%= app.downloads %></td>
        <td><%= app.rated_times %></td>
        <td><%= app.author %></td>
        <td><%= app.version %></td>
        <td><%= link_to 'Show', app %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/apps/show.html.erb
<div class="ui padded raised segment">
  <div class="ui items">
    <div class="item">
      <div class="image">
        <img src="<%= app_image(@app) %>">
      </div>
      <div class="content">
        <h1 class="header"><%= @app.name %></h1>
        <div class="meta">
          <span class="cinema"><%= @app.author %></span>
        </div>
        <div class="meta">
          <span class="version">Version <%= @app.version %></span>
        </div>
        <div class="meta">
          <span class="release">Released <%= @app.release_date.strftime("%F") %></span>
        </div>
        <div class="bottom aligned content">
          <button class="ui primary button" disabled>Download</button>
        </div>
      </div>
    </div>
  </div>
  <div class="ui divider"></div>
  <div class="ui three small statistics">
    <div class="statistic">
      <div class="value">
        <i class="small green arrow alternate circle down outline icon"></i> <%= number_to_human @app.downloads %>
      </div>
      <div class="label">
        Downloads
      </div>
    </div>
    <div class="statistic">
      <div class="value">
        <i class="small yellow star icon"></i> <%= @app.rating %>
      </div>
      <div class="label">
        Stars
      </div>
    </div>
    <div class="statistic">
      <div class="value">
        <i class="small users icon"></i> <%= number_with_delimiter @app.rated_times %>
      </div>
      <div class="label">
        Ratings
      </div>
    </div>
  </div>
  <div class="ui divider"></div>
  <h2 class="header">Description</h2>
  <div>
    <p><%= @app.description %></p>
  </div>
  <div class="ui divider"></div>
  <h2 class="header">Screenshots</h2>
  <div style="overflow-x: scroll; display: flex;">
    <img src="https://dummyimage.com/420x320/ff7f7f/333333.png&text=Sample 1" >
    <img src="https://dummyimage.com/420x320/7f7fff/333333.png&text=Sample 2" >
    <img src="https://dummyimage.com/420x320/7fff7f/333333.png&text=Sample 3" >
    <img src="https://dummyimage.com/420x320/7f7f7f/333333.png&text=Sample 4" >
  </div>
</div>

app/views/home/index.html.erb
<div class="ui raised segment search-container">
  <img class="ui centered medium image" src="/logo-text.png" >
</div>
<%= react_component("Search") %>
<%= render partial: "apps/app_cards", locals: { name: "Most Downloaded", app_list: @most_downloaded } %>
<%= render partial: "apps/app_cards", locals: { name: "Highest Rated", app_list: @highest_rated } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppGarage</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui container">
      <div class="ui stackable menu">
        <a class="header item" href="/">
          <img src="/logo.png">
          <span style="margin-left: 8px;">AppGarage</span>
        </a>
        <a class="item" href="/">Home</a>
        <a class="disabled item">Featured Apps</a>
        <a class="disabled item">Categories</a>
        <div class="right menu">
          <div class="item">
            <div class="ui secondary disabled button">Log In</div>
          </div>
          <div class="item">
            <div class="ui primary disabled button">Sign Up</div>
          </div>
        </div>
      </div>
    </div>
    <div class="ui container content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/search/index.html.erb
<div class="ui raised segment">
  <h1 class="ui header"><%= params[:query] %> (<%= @apps.count %> results)</h1>  
  <div class="ui divider"></div>
  <div class="ui divided link items">
    <% @apps.each do |app| %>
      <a class="item" href="<%= app_path(app) %>">
        <div class="small image">
          <img src="<%= app_image(app) %>">
        </div>
        <div class="content">
          <div class="header"><%= app.name %></div>
          <div class="meta">
            <span><%= app.author %></span>
          </div>
          <div class="description">
            <p><%= truncate app.description, length: 250, seperator: /\w+/ %></p>
          </div>
          <div class="extra">
            <div class="ui right floated primary button">
              View More
              <i class="right chevron icon"></i>
            </div>
            <div class="ui label"><i class="green arrow alternate circle down outline icon"></i> <%= number_to_human app.downloads %> Downloads</div>
            <div class="ui label"><i class="yellow star icon"></i> <%= app.rating %> Rating</div>
          </div>
        </div>
      </a>
    <% end %>
  </div>
</div>